/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductAddOn } from "./ProductAddOn";
import { ProductAddOnCountArgs } from "./ProductAddOnCountArgs";
import { ProductAddOnFindManyArgs } from "./ProductAddOnFindManyArgs";
import { ProductAddOnFindUniqueArgs } from "./ProductAddOnFindUniqueArgs";
import { DeleteProductAddOnArgs } from "./DeleteProductAddOnArgs";
import { ProductAddOnService } from "../productAddOn.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ProductAddOn)
export class ProductAddOnResolverBase {
  constructor(
    protected readonly service: ProductAddOnService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ProductAddOn",
    action: "read",
    possession: "any",
  })
  async _productAddOnsMeta(
    @graphql.Args() args: ProductAddOnCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ProductAddOn])
  @nestAccessControl.UseRoles({
    resource: "ProductAddOn",
    action: "read",
    possession: "any",
  })
  async productAddOns(
    @graphql.Args() args: ProductAddOnFindManyArgs
  ): Promise<ProductAddOn[]> {
    return this.service.productAddOns(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ProductAddOn, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ProductAddOn",
    action: "read",
    possession: "own",
  })
  async productAddOn(
    @graphql.Args() args: ProductAddOnFindUniqueArgs
  ): Promise<ProductAddOn | null> {
    const result = await this.service.productAddOn(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductAddOn)
  @nestAccessControl.UseRoles({
    resource: "ProductAddOn",
    action: "delete",
    possession: "any",
  })
  async deleteProductAddOn(
    @graphql.Args() args: DeleteProductAddOnArgs
  ): Promise<ProductAddOn | null> {
    try {
      return await this.service.deleteProductAddOn(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
