/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductOrder } from "./ProductOrder";
import { ProductOrderCountArgs } from "./ProductOrderCountArgs";
import { ProductOrderFindManyArgs } from "./ProductOrderFindManyArgs";
import { ProductOrderFindUniqueArgs } from "./ProductOrderFindUniqueArgs";
import { DeleteProductOrderArgs } from "./DeleteProductOrderArgs";
import { ProductOrderService } from "../productOrder.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ProductOrder)
export class ProductOrderResolverBase {
  constructor(
    protected readonly service: ProductOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "read",
    possession: "any",
  })
  async _productOrdersMeta(
    @graphql.Args() args: ProductOrderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ProductOrder])
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "read",
    possession: "any",
  })
  async productOrders(
    @graphql.Args() args: ProductOrderFindManyArgs
  ): Promise<ProductOrder[]> {
    return this.service.productOrders(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ProductOrder, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "read",
    possession: "own",
  })
  async productOrder(
    @graphql.Args() args: ProductOrderFindUniqueArgs
  ): Promise<ProductOrder | null> {
    const result = await this.service.productOrder(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductOrder)
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "delete",
    possession: "any",
  })
  async deleteProductOrder(
    @graphql.Args() args: DeleteProductOrderArgs
  ): Promise<ProductOrder | null> {
    try {
      return await this.service.deleteProductOrder(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
